name: Run PlayState code bleh
    
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install hjson4haxe
        run: |
          haxelib git hjson4haxe https://github.com/anthonydudeh/hjson4haxe

      - name: Verify libs
        run: haxelib list

      - name: Run PlayState.hx
        run: |
          HAXELIB_SRC="$(haxelib config)/hjson4haxe/git/src"
          haxe -cp source -cp "$HAXELIB_SRC" -main PlayState --interp
 
 
